kind: pipeline
name: Rebase Kernel

clone:
  depth: 1

steps:
- name: building
  image: xyzuan/xdocker:latest
  environment:
    bot_token:
      from_secret: bot_token
    chat_id:
      from_secret: chat_id
  commands:
  - bash compile.sh
